services:
  promptforge-dev:
    image: node:latest
    container_name: promptforge-dev
    volumes:
      - "./:/app"
    working_dir: /app
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - "3072:3000"